apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app-container
          image: my-simple-react-app  # Use the image name and tag you built earlier
          ports:
            - containerPort: 3000  # Adjust the port as needed